services:
  - type: web
    name: cert-one-backend
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        value: "*"
      - key: MAX_FILE_SIZE
        value: 52428800
      - key: DEFAULT_BLOCKCHAIN
        value: "Bitcoin (OpenTimestamps)"
      - key: OTS_API_URL
        value: https://ots.tools/api/v1
      - key: OTS_TIMEOUT
        value: 30000
      # Puppeteer configuration for Docker
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/chromium-browser"
      - key: PUPPETEER_DISABLE_HEADLESS_WARNING
        value: "true"
      # Add these as secret environment variables in Render dashboard:
      # - PINATA_JWT (recommended - newer, more secure)
      # - PINATA_API_KEY
      # - PINATA_SECRET_KEY
      # - JWT_SECRET
      # - WEB3_STORAGE_TOKEN (optional)
      # - GITHUB_TOKEN (optional)
