const fs = require('fs');
const path = require('path');
const handlebars = require('handlebars');
const puppeteer = require('puppeteer');

// Helper function to find template path
function findTemplatePath() {
  const possiblePaths = [
    path.join(__dirname, '../templates/cert.hbs'),
    path.join(__dirname, '../../templates/cert.hbs'),
    path.join(process.cwd(), 'templates/cert.hbs'),
    path.join(process.cwd(), 'backend/templates/cert.hbs')
  ];
  
  for (const templatePath of possiblePaths) {
    if (fs.existsSync(templatePath)) {
      return templatePath;
    }
  }
  
  throw new Error('Certificate template not found. Checked paths: ' + possiblePaths.join(', '));
}

// Helper function to cleanup browser resources
async function cleanup(page, browserInstance) {
  try {
    if (page) {
      await page.close();
    }
    if (browserInstance) {
      await browserInstance.close();
    }
  } catch (error) {
    console.warn('Cleanup warning:', error.message);
  }
}

// Helper function to find Chromium executable
function findChromiumExecutable() {
  const { execSync } = require('child_process');
  
  // Check common system Chrome locations
  const chromePaths = [
    '/usr/bin/google-chrome',
    '/usr/bin/chromium-browser',
    '/usr/bin/chrome',
    '/usr/bin/chromium',
    '/snap/bin/chromium',
    '/opt/google/chrome/chrome'
  ];
  
  for (const chromePath of chromePaths) {
    if (fs.existsSync(chromePath)) {
      console.log('Found system Chrome at:', chromePath);
      return chromePath;
    }
  }
  
  // Try to find via which command
  try {
    const chromePath = execSync('which google-chrome || which chromium-browser || which chrome', { encoding: 'utf8' }).trim();
    if (chromePath && fs.existsSync(chromePath)) {
      console.log('Found system Chrome via which:', chromePath);
      return chromePath;
    }
  } catch (error) {
    console.log('No system Chrome found via which command');
  }
  
  return null;
}

// Fallback PDF generation using a simple approach
async function generatePdfFallback(data) {
  console.log('Using fallback PDF generation method...');
  
  // Read and compile template
  const templatePath = findTemplatePath();
  const templateHtml = fs.readFileSync(templatePath, 'utf8');
  const compile = handlebars.compile(templateHtml);
  const html = compile(data);
  
  // Create a simple HTML document with embedded styles
  const fullHtml = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 40px;
      line-height: 1.6;
      color: #333;
    }
    .title {
      font-size: 24px;
      font-weight: bold;
      margin-bottom: 30px;
      text-align: center;
      border-bottom: 2px solid #333;
      padding-bottom: 10px;
    }
    .field {
      margin-bottom: 15px;
      padding: 8px 0;
      border-bottom: 1px solid #eee;
    }
    .label {
      font-weight: bold;
      color: #555;
      display: inline-block;
      width: 150px;
    }
    .value {
      color: #333;
    }
    .footer {
      margin-top: 40px;
      text-align: center;
      font-size: 12px;
      color: #666;
    }
  </style>
</head>
<body>
  <div class="title">CERT.ONE Certificate</div>
  <div class="field"><span class="label">User:</span> <span class="value">${data.userName}</span></div>
  <div class="field"><span class="label">Email:</span> <span class="value">${data.email}</span></div>
  <div class="field"><span class="label">Title:</span> <span class="value">${data.title}</span></div>
  <div class="field"><span class="label">File Name:</span> <span class="value">${data.fileName}</span></div>
  <div class="field"><span class="label">Certificate ID:</span> <span class="value">${data.certificateId}</span></div>
  <div class="field"><span class="label">File Hash:</span> <span class="value">${data.fileHash}</span></div>
  <div class="field"><span class="label">Timestamp:</span> <span class="value">${data.timestamp}</span></div>
  <div class="field"><span class="label">Blockchain:</span> <span class="value">${data.blockchain}</span></div>
  <div class="field"><span class="label">Verify:</span> <span class="value">${data.verificationLink}</span></div>
  <div class="footer">
    Generated by CERT.ONE - Blockchain Certificate Service
  </div>
</body>
</html>`;
  
  // For now, return the HTML as a buffer (this is a temporary fallback)
  // In a production environment, you might want to use a different PDF library
  console.log('Fallback method: Returning HTML content (PDF generation not available)');
  return Buffer.from(fullHtml, 'utf8');
}

async function generatePdf(data) {
  let browserInstance;
  let page;

  try {
    console.log('Starting PDF generation with data:', data);
    
    // Validate input data
    if (!data || typeof data !== 'object') {
      throw new Error('Invalid data provided for PDF generation');
    }

    // Read and compile template
    const templatePath = findTemplatePath();
    console.log('Using template at:', templatePath);
    
    const templateHtml = fs.readFileSync(templatePath, 'utf8');
    console.log('Template loaded successfully');
    
    const compile = handlebars.compile(templateHtml);
    const html = compile(data);
    console.log('Template compiled successfully');

    // Launch browser with proper configuration
    console.log('Launching Puppeteer browser...');
    console.log('Puppeteer version:', require('puppeteer/package.json').version);
    
    const launchOptions = {
      headless: 'new',
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-gpu',
        '--no-first-run',
        '--no-zygote',
        '--deterministic-fetch',
        '--disable-features=IsolateOrigins',
        '--disable-site-isolation-trials',
        '--disable-blink-features=AutomationControlled'
      ],
      ignoreHTTPSErrors: true,
      timeout: 30000
    };
    
    // Try to find Chrome executable
    const chromePath = findChromiumExecutable();
    if (chromePath) {
      launchOptions.executablePath = chromePath;
      console.log('Using system Chrome executable:', chromePath);
    } else {
      console.log('No system Chrome found, will try bundled Chromium');
      
      // Check if bundled Chromium exists
      const puppeteerPath = path.dirname(require.resolve('puppeteer'));
      const chromiumPaths = [
        path.join(puppeteerPath, '.local-chromium'),
        path.join(puppeteerPath, 'chromium'),
        path.join(puppeteerPath, '.cache', 'chrome')
      ];
      
      let chromiumFound = false;
      for (const chromiumPath of chromiumPaths) {
        if (fs.existsSync(chromiumPath)) {
          console.log('Found bundled Chromium at:', chromiumPath);
          chromiumFound = true;
          break;
        }
      }
      
      if (!chromiumFound) {
        console.log('No bundled Chromium found, attempting to install...');
        // Try to install Chromium
        const { execSync } = require('child_process');
        try {
          execSync('npx puppeteer browsers install chrome', { stdio: 'inherit' });
          console.log('Chromium installation completed');
        } catch (error) {
          console.error('Failed to install Chromium:', error.message);
          console.log('Falling back to alternative PDF generation method...');
          return await generatePdfFallback(data);
        }
      }
    }
    
    console.log('Launch options:', JSON.stringify(launchOptions, null, 2));
    
    browserInstance = await puppeteer.launch(launchOptions);
    console.log('Browser launched successfully');

    page = await browserInstance.newPage();
    console.log('New page created');
    
    // Set content with timeout handling
    console.log('Setting page content...');
    await page.setContent(html, {
      waitUntil: ['networkidle0', 'domcontentloaded'],
      timeout: 30000
    });
    console.log('Content set on page');

    // Generate PDF with A4 format
    console.log('Generating PDF...');
    const pdfBuffer = await page.pdf({ 
      format: 'A4',
      margin: {
        top: '20mm',
        right: '20mm',
        bottom: '20mm',
        left: '20mm'
      },
      printBackground: true,
      preferCSSPageSize: true,
      timeout: 30000
    });

    console.log(`PDF generated successfully, size: ${pdfBuffer.length} bytes`);
    return pdfBuffer;

  } catch (error) {
    console.error('PDF generation error:', error);
    console.error('Error name:', error.name);
    console.error('Error message:', error.message);
    console.error('Stack trace:', error.stack);
    
    // Check for specific Puppeteer errors
    if (error.message && error.message.includes('executable')) {
      console.error('Chrome/Chromium executable not found. Please ensure Chrome is installed or set PUPPETEER_EXECUTABLE_PATH');
    }
    
    if (error.message && error.message.includes('timeout')) {
      console.error('PDF generation timed out. This might be due to slow system resources.');
    }
    
    if (error.message && error.message.includes('ECONNREFUSED')) {
      console.error('Connection refused. This might be a network or firewall issue.');
    }
    
    // Log environment info for debugging
    console.error('Environment info:');
    console.error('- Node version:', process.version);
    console.error('- Platform:', process.platform);
    console.error('- Architecture:', process.arch);
    console.error('- Current working directory:', process.cwd());
    console.error('- PUPPETEER_EXECUTABLE_PATH:', process.env.PUPPETEER_EXECUTABLE_PATH || 'not set');
    
    // Try fallback method
    console.log('Attempting fallback PDF generation...');
    try {
      return await generatePdfFallback(data);
    } catch (fallbackError) {
      console.error('Fallback PDF generation also failed:', fallbackError);
      throw new Error(`PDF generation failed: ${error.message}`);
    }
  } finally {
    // Cleanup resources
    await cleanup(page, browserInstance);
  }
}

module.exports = generatePdf;
